### ISSUE TITLE
Reports not working.

### ISSUE THREAD

**Issue by mkaliyannan** [vatesfr/xo-server-backup-reports#7]
I configured as per the instructions. 

![image](https://cloud.githubusercontent.com/assets/8954012/13165196/3028dd66-d678-11e5-84cf-47fee76dd19c.png)

I configued and not able to trace the logs files. I didn't recieved any mails. How I debug the issue ?. How to verify the testmail ?

**Comment by julien-f** [comment]
Update xo-server-transport-email to 0.0.5, it gives explicit error messages on the server's console.

**Comment by olivierlambert** [comment]
Probably fixed by the last `xo-server-transport-email` release.
